version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
    - MYSQL_DATABASE=db_name
    - MYSQL_USER=usr_default
    - MYSQL_PASSWORD=mpass
    - MYSQL_HOST=127.0.0.1
    ports:
    - "8080:80"
    volumes:
    - .:/var/www
    depends_on:
    - db

  db:
    image: mysql:8.0.11
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=mpass
    - MYSQL_USER=usr_default
    - MYSQL_PASSWORD=mpass
    - MYSQL_DATABASE=db_name
    volumes:
    - "mysql_data:/var/lib/mysql"
    - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }

